### ISSUE TITLE
Filters out characters such as "é", "ç", "à", ...

### ISSUE THREAD

**Issue by AntonioVdlC** [jonschlinkert/dashify#4]
Hi Jon,

I was looking at your module for a small side project I am working on and I like the fact that it does what it says it does. Unfortunately, for my use case it seems to filter out characters that I would need to be in the "dashified" string. 

For example:

``` javascript
dashify("São Tomé and Príncipe")
// yields "s-o-tom--and-pr-ncipe" instead of "são-tomé-and-príncipe"
```

I have written a local version of `dashify` for my side project, but I was wondering if it would be helpful to open a PR and append those changes to your module. If it is not a change that is in line with the philosophy of the module, please feel free to close this issue. 

Thanks again! 😃

**Comment by jonschlinkert** [comment]
yes, a pr would be great! thanks

**Comment by erikpukinskis** [comment]
This PR should fix this issue: https://github.com/jonschlinkert/dashify/pull/6
