### ISSUE TITLE
[Bug] Fails to minify on npm build

### ISSUE THREAD

**Issue by kevin-lindsay-1** [jonschlinkert/dashify#8]
Using `node v8.2.1` and `npm 5.3.0`

Error message:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/dashify/index.js:17
```

**Comment by doowb** [comment]
This library doesn't do any minifying. You probably need to configure your build system to do something differently. The error is pointing to line 17 which has es6 syntax, so the minifier you're using needs to support es6 syntax or at least have a plugin that supports it.
