### ISSUE TITLE
No longer works in ie11

### ISSUE THREAD

**Issue by hipstersmoothie** [jonschlinkert/dashify#9]
The use of fat arrows has broken my builds for ie11

**Comment by hipstersmoothie** [comment]
Correction: It's not common practice to babel-ify your npm dependancies. You're now the only *special* snowflake in our config that needs to be transpiled to es5. Good job bro

**Comment by petermikitsh** [comment]
🍿

**Comment by petermikitsh** [comment]
It looks the ES6 arrow function was added in this [commit](https://github.com/jonschlinkert/dashify/commit/cbc0908e90636692751a117d8cae443164374df5).

**Comment by petermikitsh** [comment]
It looks like the ES6 arrow function was added in this [commit](https://github.com/jonschlinkert/dashify/commit/cbc0908e90636692751a117d8cae443164374df5).
